#Procesos de automatizacion
name: Deploy de la pagina
#que eventos van a disparar la ejecucion del proceso
on: 
  push:
    branches: 
      - main  #Cada vez que se haga un push a main
#Tareas a realizar
jobs:
#ID
  deploy-page:
   #Entorno, no es local / sv de github
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout 
        uses: actions/checkout@v2.3.1

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        width:
            branch: gh-pages # The branch the action should deploy to
            folder: . #The folder the action should deploy